### ISSUE TITLE
expose IncomingConnection::new

### ISSUE THREAD

**Issue by GlenDC** [tun2proxy/socks5-impl#3]
Thank you for creating this crate. Would you be open to a contribution where I make the `IncomingConnection::new` constructor public?

I ask as I would like to create the connection directly from a TcpStream, as in my use case I want to manage everything in front of it myself. As in, I already have my own listener that I want to use, and would like to just turn a stream into a Socks5 connection.

Currently I cannot do such a thing with your crate. I could fork it, but that seems a bit drastic for such a minor need and on top of that it is probably better for all of I can continue to contribute to this crate.

I'm willing to make the PR. Just wanted to check if you're open to that...

**Comment by ssrlive** [comment]
Welcome. Feel free to PR. But notice that there are two situations: async and not async.

**Comment by GlenDC** [comment]
Sure. I'm interested in the async one, but sure, I can do both.

Question. Is there a difference with https://crates.io/crates/socks5-server? That one also seems to provide a socks5-proto crate.

Why would one use one over the other project? Seems like that one is also actively maintained, and it's similar to yours?

**Comment by ssrlive** [comment]
I forked from that project because my pull request was rejected by the crate. I tried to communicate with the author through Telegram, but the communication was extremely difficult and most of my suggestions were rejected. Consequently, I had to give up. I couldn't afford to waste time waiting, so I rewrote the code and deployed my own version. I also borrowed another implementation of the client to ensure a complete implementation of the SOCKS5 protocol.

As a result, you can see that the client's implementation differs somewhat from the server's. If you have the time and interest, you can modify the client's code to match the style of the server.

**Comment by GlenDC** [comment]
In that case I'm going for now try to use socks5 proto, as I don't need the server or client implementation.

As such better I do not contribute the proposed change yet to here as I would be as the only use case not be using it.

Thank you for your friendly welcome and precious time. Take care.

**Comment by ssrlive** [comment]
Nerver mind. You are welcome.
